version: '2'

services:

  seleniumhub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=5
      - GRID_TIMEOUT=5
      - SE_OPTS=-browserTimeout 5 -timeout 5
    container_name: seleniumhub

  chromenode:
    image: selenium/node-chrome
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - seleniumhub

  gherkin:
    build: ./
    volumes:
      - ${PATH_TO_BDD}:/usr/app
    depends_on:
      - chromenode
      - seleniumhub
    links:
      - seleniumhub
