version: '2'

services:

  seleniumhub:
    image: selenium/hub
    ports:
      - "4444:4444"
    container_name: seleniumhub
    volumes:
      - /dev/urandom:/dev/random

#  firefoxnode:
#    image: selenium/node-firefox
#    ports:
#      - 5900
#    environment:
#      - HUB_PORT_4444_TCP_ADDR=seleniumhub
#      - HUB_PORT_4444_TCP_PORT=4444
#    depends_on:
#      - seleniumhub

  chromenode:
    image: selenium/node-chrome
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/urandom:/dev/random
    depends_on:
      - seleniumhub

  gherkin:
    build: ./
    volumes:
      - ${PATH_TO_BDD}:/usr/app
      - /dev/urandom:/dev/random
    depends_on:
#      - firefoxnode
      - chromenode
      - seleniumhub
